apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share/k3s/tempo
    server: 172.16.16.6