apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-ca
  namespace: kube-system
data:
  harbor.crt: |+
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTakNDQWpLZ0F3SUJBZ0lRUUdweEVXa1lzYUpmNzJLa2gyY2NQVEFOQmdrcWhraUc5dzBCQVFzRkFEQVUKTVJJd0VBWURWUVFERXdsb1lYSmliM0l0WTJFd0hoY05NalF4TURBNE1USTFNakUxV2hjTk1qVXhNREE0TVRJMQpNakUxV2pBa01TSXdJQVlEVlFRREV4bG9ZWEppYjNJdWFXNTBaWEp1YzJ0dmJXUmhMbU5zYjNWa01JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVKcFJ5Q1VhdDdPdHJ1R1lQeTV0bDNsOXp0cFcKMXA0RjFrVlM5dDBxaGYzamZza2orR3RaODhxVDR6K0hkdUU4Y3luWlVHOGIrUm5SUExoVTlVY3RXSUlORVdYZworUE9QbVF4Z1R5R2xJMHUwMkpyUGNuQ1pEYWdmckZoWWRaZ2V1VCtmR096VXhUTE16TVBmSTU3eGxTSlV4cUhDCkFXejVudEgybEgzK0w3WmlNcGpxUHJQZXVJZUZhNjdmWUh4OTNSOEhLcHZiQkNmYkcrd3V4ZFZTdHUxZVZ1V3YKR1pBWXJNejlhQjBDdjZTZGI1RmFjcjYxZmFyQjBiMGo5c2R3dU1IM0x4a0QvZjgyWVFocHhQaGZBeWZXalNveAoxbVR1TGljc2ozK1FiYzdIc3NJQ25lSGdLd2RjRXVrTlZGTUE0SDF5Nm1uYzN6REFTUXgyRkdFbTVRSURBUUFCCm80R0hNSUdFTUE0R0ExVWREd0VCL3dRRUF3SUZvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUIKQlFVSEF3SXdEQVlEVlIwVEFRSC9CQUl3QURBZkJnTlZIU01FR0RBV2dCUko2dVJJdW96c0JzVjZiajZCYWd5MwpCMXV1MHpBa0JnTlZIUkVFSFRBYmdobG9ZWEppYjNJdWFXNTBaWEp1YzJ0dmJXUmhMbU5zYjNWa01BMEdDU3FHClNJYjNEUUVCQ3dVQUE0SUJBUUNsbHRXQ2g2LzVwcU9RTEwwRjRYOE1HMG9LWjJaNndTSDlvTUg0OHFrWFMwQncKeWNlYTdXS3I2cGwwV08vaWhOTE9ZRi9tV1dFL1RPd2VnQnh1enpWVmIrVFh5b1ZLdTlKSzY4Mm1DVVVidTZEVQpLRHM5VEttK3FtRFhicGpUeE1vd0p0eXdMVkxDbWxWZHJ1TnNkdGpSdXZyclVVblR2cVh0Uk0zT0wwRDJoM25JClh1YTc1cndjaUdVMENPZk90MkZwT1pxdVBDYkNKWm4vS1JmWldoL2pBeVVsNjBwM3RMeUVKaFhtQ3ptZkVzbUQKUXRmUFBWV0tDeWhwVHhBdmM4UXVIa2dNbkRVTEltNmNHSndVb3psR0k3V2ZDcDJ0WFlvZ2tYK2RVNlhWeUpLUwo4djBISkluSHdyTmwvRXVlNWd6MGIwdURhbnFyUGcramorVTVsRlBsCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-script
  namespace: kube-system
data:
  setup.sh: |
    echo "$TRUSTED_CERT_1" | base64 --decode > /usr/local/share/ca-certificates/harbor.crt
    echo "172.16.16.200 harbor.internskomda.cloud" >> /etc/hosts
    update-ca-certificates
    systemctl restart containerd
    systemctl restart k3s-agent.service || true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: trusted-ca-setup
  labels:
    k8s-app: trusted-ca-setup
spec:
  selector:
    matchLabels:
      k8s-app: trusted-ca-setup
  template:
    metadata:
      labels:
        k8s-app: trusted-ca-setup
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: init-node
        command: ["nsenter"]
        args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "$(SETUP_SCRIPT)"]
        image: debian
        env:
        - name: TRUSTED_CERT_1
          valueFrom:
            configMapKeyRef:
              name: trusted-ca
              key: harbor.crt
        - name: SETUP_SCRIPT
          valueFrom:
            configMapKeyRef:
              name: setup-script
              key: setup.sh
        securityContext:
          privileged: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1
