apiVersion: v1
kind: Service
metadata:
  labels:
    app: harbor
  name: harbor
  namespace: harbor
spec:
  ports:
  - name: http
    nodePort: 30002
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: harbor
    component: nginx
    release: harbor
  sessionAffinity: None
  type: NodePort
