apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: inventory-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis
  clusterIP: None