apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: prometheus-server
    namespace: monitoring
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share/k3s/prometheus
    server: 172.16.16.6