apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: haproxy-kubernetes-ingress
    meta.helm.sh/release-namespace: haproxy-controller
  labels:
    app.kubernetes.io/instance: haproxy-kubernetes-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/version: 3.0.1
    helm.sh/chart: kubernetes-ingress-1.41.0
  name: haproxy-kubernetes-ingress
  namespace: haproxy-controller
spec:
  clusterIP: 10.43.54.230
  clusterIPs:
  - 10.43.54.230
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 30698
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 31696
    port: 443
    protocol: TCP
    targetPort: https
  - appProtocol: https
    name: quic
    nodePort: 31696
    port: 443
    protocol: UDP
    targetPort: quic
  - name: stat
    nodePort: 31884
    port: 1024
    protocol: TCP
    targetPort: stat
  - name: prometheus
    nodePort: 32519
    port: 6060
    protocol: TCP
    targetPort: prometheus
  selector:
    app.kubernetes.io/instance: haproxy-kubernetes-ingress
    app.kubernetes.io/name: kubernetes-ingress
  sessionAffinity: None
  type: LoadBalancer
